### ISSUE TITLE
Map not Aligned

### ISSUE THREAD

**Issue by thebirdgr** [mech0ctopus/rrt-global-planner#5]
Hey appreciate your work.

However, upon building it and running the example, I realized that the laser scan and the map aren't aligned like in your demo. This is causing the planning to fail. Is there any configuration that i might have missed?

I have only changed the planner_frequency to 0.

![map_not_aligned](https://github.com/mech0ctopus/rrt-global-planner/assets/60645728/16888d2e-1e9a-4a71-a6d0-a2cdde396d1f)

**Comment by mech0ctopus** [comment]
Hey @thebirdgr, after launching you can use the "2D Pose Estimate" button in RViz to  re-position the robot until the scan and map look approximately aligned. Then use "2D Nav Goal" and the planner should succeed.

**Comment by thebirdgr** [comment]
Thanks for the quick response! That's something new. I have tried it and have got it to a reasonably close estimate. However I still get the following error:

`Generating Global Plan with RRT.
[ INFO] [1716817842.708513588, 109.817000000]: Failed to find Global Plan with RRT`

I realise it happens in another documented issue as well but i can't use the solution there to solve it. Do you have an idea?

**Comment by mech0ctopus** [comment]
Ah! Yeah, in `rrt-global-planner/params/rrt_global_planner.yaml` try setting `K_in` (max. number of iterations/vertices) to something large (like 20,000).

Let me know if this solves the issue and I'll update the README and `.yaml`.

**Comment by thebirdgr** [comment]
Ps slept as it was late. So far it seems to slow down the planning. There is definitely a higher chance of the planning being made. To me it looks good, I just need to fix the way my robot moves.

**Comment by mech0ctopus** [comment]
I think slower planning is expected behavior since we're increasing the max. number of iterations.

You might also want to experiment with `d` parameter which defines how far to extend the tree on each iteration. Larger `d` values may shorten the planning time.

A larger `goal_tol` value will also increase the likelihood of a successful planning attempt.

**Comment by thebirdgr** [comment]
Sure thank you. I have used it for testing out a learning project. For now I wouldn't be testing the parameters further for a long time, however, if I do, I will update this thread.
